In [1]:
import numpy as np

In [2]:
matrix = np.array(
    [[1,1,1,2,1,1,2,1],
     [1,2,2,2,2,2,2,1],
     [1,1,1,2,1,2,2,1],
     [1,1,2,3,1,2,3,1],
     [1,1,3,1,1,3,1,2],
     [2,1,3,1,3,2,2,1],
     [2,2,2,2,2,1,2,1],
     [2,2,3,2,1,3,1,3]]
)
matrix = matrix*10
print(matrix)

[[10 10 10 20 10 10 20 10]
 [10 20 20 20 20 20 20 10]
 [10 10 10 20 10 20 20 10]
 [10 10 20 30 10 20 30 10]
 [10 10 30 10 10 30 10 20]
 [20 10 30 10 30 20 20 10]
 [20 20 20 20 20 10 20 10]
 [20 20 30 20 10 30 10 30]]


In [3]:
padded = np.pad(matrix,pad_width=2,mode='reflect')
print(padded)

[[10 10 10 10 10 20 10 20 20 10 20 20]
 [20 20 10 20 20 20 20 20 20 10 20 20]
 [10 10 10 10 10 20 10 10 20 10 20 10]
 [20 20 10 20 20 20 20 20 20 10 20 20]
 [10 10 10 10 10 20 10 20 20 10 20 20]
 [20 10 10 10 20 30 10 20 30 10 30 20]
 [30 10 10 10 30 10 10 30 10 20 10 30]
 [30 10 20 10 30 10 30 20 20 10 20 20]
 [20 20 20 20 20 20 20 10 20 10 20 10]
 [30 20 20 20 30 20 10 30 10 30 10 30]
 [20 20 20 20 20 20 20 10 20 10 20 10]
 [30 10 20 10 30 10 30 20 20 10 20 20]]


In [5]:
kernel = [[1,1,1],
          [1,0,0],
          [1,0,0]]

In [6]:
y, x = padded.shape
y = y - 2
x = x - 2
new_mat = np.zeros((y,x))
for i in range(y):
    for j in range(x):
        new_mat[i][j] = np.sum(padded[i:i+3, j:j+3]*kernel)
print(new_mat)

[[ 60.  60.  50.  70.  70.  90.  80.  80.  90.  70.]
 [ 80.  80.  70.  90.  90. 100.  90.  80.  90.  70.]
 [ 60.  60.  50.  70.  70.  80.  70.  80.  90.  60.]
 [ 80.  70.  70.  80.  90. 110.  80.  90. 100.  70.]
 [ 80.  50.  50.  60.  90.  90.  70. 100.  90.  80.]
 [100.  50.  70.  80. 120.  80. 100. 110. 100.  90.]
 [100.  60.  90.  80. 100.  80. 100.  90.  80.  80.]
 [110.  80. 100.  90. 120. 100. 100.  90.  80.  90.]
 [110. 100. 100. 100. 110.  90.  80.  80.  80.  80.]
 [120.  90. 110. 100. 110.  90. 100. 100.  90.  90.]]
