# Edge detection Kernels

### Prewitt operator

For Ix(x,y)

    ⎡−1  0  1⎤
    ⎢-1  0  1⎥
    ⎣-1  0  1⎦
For Iy

    ⎡−1 −1 -1⎤
    ⎢ 0  0  0⎥
    ⎣ 1  1  1⎦


### Sobel operator

For Ix(x,y)

    ⎡−1  0  1⎤
    ⎢-2  0  2⎥
    ⎣-1  0  1⎦

For Iy(x,y)

    ⎡−1 −2 -1⎤
    ⎢ 0  0  0⎥
    ⎣ 1  2  1⎦

### Laplacian

    ⎡ 0  1  0⎤
    ⎢ 1 -4  1⎥
    ⎣ 0  1  0⎦

### hit or miss

    ⎡ 0  1  0⎤
    ⎢ 1 -1  1⎥
    ⎣ 0  1  0⎦

In [1]:
import numpy as np

In [2]:
image = np.array(
    [[1,1,1,1,1,1,1,1,1,1,1,1,1,1],
     [1,1,1,1,1,1,0,0,1,1,1,1,1,1],
     [1,1,1,1,1,0,0,0,0,0,1,1,1,1],
     [1,1,1,1,0,0,0,0,0,1,1,1,1,1],
     [1,1,1,1,0,0,0,0,0,0,0,1,1,1],
     [1,1,0,0,0,0,0,0,0,1,1,1,1,1],
     [1,1,0,0,0,0,0,0,0,0,0,0,1,1],
     [1,1,1,1,1,0,0,0,0,1,0,1,1,1],
     [1,1,0,1,0,0,0,0,0,1,0,1,1,1],
     [1,1,0,0,0,0,0,0,0,0,0,1,1,1],
     [1,1,1,1,0,1,1,1,0,1,1,1,1,1],
     [1,1,1,1,1,1,1,1,0,1,1,1,1,1],
     [1,1,1,1,1,1,1,1,1,1,1,1,1,1]]
)

In [3]:
kernel = np.array(
    [[0,1,0],
     [1,-1,1],
     [0,1,0]]
)

In [5]:
image = image*255

In [8]:
image = image.astype('uint8')

In [10]:
y, x = image.shape
y = y - 2
x = x - 2
new_mat = np.zeros((y,x),dtype='uint8')
for i in range(y):
    for j in range(x):
        new_mat[i][j] = np.sum(image[i:i+3, j:j+3]*kernel)
print(new_mat)

[[253 253 253 253 255 254 254 255 254 253 253 253]
 [253 253 253 255 254   0   0 255 253 254 253 253]
 [253 253 254 254   0   0   0 255   0 254 253 253]
 [253 254 255 255   0   0   0   0 254 253 254 253]
 [254 254 255   0   0   0   0 255   0 255 254 253]
 [254 254 255 255   0   0   0   0 254 255 253 254]
 [253 255 254   0 255   0   0 255   0 254 255 253]
 [254 253   0 254   0   0   0 255   0 254 254 253]
 [254 254 254   0 255 255 255   0 254 254 254 253]
 [253 254 255 253 255 254 255 254 255 254 253 253]
 [253 253 253 254 253 253 254 253 254 253 253 253]]
